// src/layout/Layout.vue
<script setup lang="ts">
import { useRouter } from 'vue-router'
import { useAuthStore } from '@/features/auth/stores/auth-store'

const router = useRouter()
const auth = useAuthStore()

function logout() {
  auth.logout()
  router.push('/login')
}

const navItems = [
  { to: '/', label: 'Dashboard', icon: '📊' },
  { to: '/users', label: 'Users', icon: '👥' },
  { to: '/poems', label: 'Poems', icon: '📝' },
  { to: '/emotions', label: 'Emotions', icon: '💜' },
  { to: '/emotion-catalog', label: 'Emotion Catalog', icon: '🗂️' },
  { to: '/likes', label: 'Likes', icon: '❤️' },
  { to: '/bookmarks', label: 'Bookmarks', icon: '🔖' },
]
</script>

<template>
  <div class="flex h-screen bg-gray-100">
    <!-- Sidebar -->
    <aside class="w-64 bg-purple-900 text-white flex flex-col">
      <div class="px-6 py-5 border-b border-purple-700">
        <h1 class="text-xl font-bold tracking-wide">Oda Admin</h1>
      </div>
      <nav class="flex-1 py-4">
        <router-link
          v-for="item in navItems"
          :key="item.to"
          :to="item.to"
          class="flex items-center gap-3 px-6 py-3 text-sm hover:bg-purple-800 transition-colors"
          active-class="bg-purple-700 font-semibold"
        >
          <span>{{ item.icon }}</span>
          {{ item.label }}
        </router-link>
      </nav>
      <div class="px-6 py-4 border-t border-purple-700">
        <p class="text-xs text-purple-300 mb-2">{{ auth.user?.email }}</p>
        <button
          @click="logout"
          class="w-full text-left text-sm text-purple-200 hover:text-white"
        >
          Sign out →
        </button>
      </div>
    </aside>

    <!-- Content -->
    <main class="flex-1 overflow-auto">
      <router-view />
    </main>
  </div>
</template>

// src/components/Layout.tsx
import { NavLink, Outlet, useNavigate } from 'react-router-dom'
import { useAuthStore } from '@/store/auth-store'

const navItems = [
  { to: '/dashboard', label: 'Dashboard' },
  { to: '/users', label: 'Users' },
  { to: '/poems', label: 'Poems' },
  { to: '/likes', label: 'Likes' },
  { to: '/bookmarks', label: 'Bookmarks' },
  { to: '/emotions', label: 'Emotions' },
  { to: '/emotion-catalog', label: 'Cat. Emociones' },
]

export default function Layout() {
  const { logout } = useAuthStore()
  const navigate = useNavigate()

  const handleLogout = () => {
    logout()
    navigate('/login')
  }

  return (
    <div className="flex h-screen bg-gray-100">
      {/* Sidebar */}
      <aside className="w-56 bg-gray-900 text-white flex flex-col">
        <div className="p-4 text-xl font-bold border-b border-gray-700">Oda Admin</div>
        <nav className="flex-1 p-2 space-y-1">
          {navItems.map((item) => (
            <NavLink
              key={item.to}
              to={item.to}
              className={({ isActive }) =>
                `block px-3 py-2 rounded text-sm font-medium transition-colors ${
                  isActive
                    ? 'bg-indigo-600 text-white'
                    : 'text-gray-300 hover:bg-gray-700'
                }`
              }
            >
              {item.label}
            </NavLink>
          ))}
        </nav>
        <button
          onClick={handleLogout}
          className="m-3 px-3 py-2 rounded text-sm font-medium text-gray-300 hover:bg-gray-700 text-left"
        >
          Logout
        </button>
      </aside>

      {/* Main */}
      <main className="flex-1 overflow-auto p-6">
        <Outlet />
      </main>
    </div>
  )
}
