// src/components/Pagination.vue
<script setup lang="ts">
const props = defineProps<{ page: number; total: number; limit: number }>()
const emit = defineEmits<{ (e: 'change', page: number): void }>()

const totalPages = () => Math.ceil(props.total / props.limit)
</script>

<template>
  <div class="flex items-center gap-2 mt-4">
    <button
      :disabled="page <= 1"
      @click="emit('change', page - 1)"
      class="px-3 py-1 rounded bg-gray-200 disabled:opacity-40 hover:bg-gray-300"
    >
      ←
    </button>
    <span class="text-sm text-gray-600">
      Page {{ page }} of {{ totalPages() }} ({{ total }} total)
    </span>
    <button
      :disabled="page >= totalPages()"
      @click="emit('change', page + 1)"
      class="px-3 py-1 rounded bg-gray-200 disabled:opacity-40 hover:bg-gray-300"
    >
      →
    </button>
  </div>
</template>

// src/components/Pagination.tsx
interface Props {
  page: number
  totalPages: number
  onPage: (p: number) => void
}

export default function Pagination({ page, totalPages, onPage }: Props) {
  if (totalPages <= 1) return null
  return (
    <div className="flex gap-1 mt-4 justify-end">
      <button
        disabled={page === 1}
        onClick={() => onPage(page - 1)}
        className="px-3 py-1 rounded border text-sm disabled:opacity-40"
      >
        Prev
      </button>
      <span className="px-3 py-1 text-sm">
        {page} / {totalPages}
      </span>
      <button
        disabled={page === totalPages}
        onClick={() => onPage(page + 1)}
        className="px-3 py-1 rounded border text-sm disabled:opacity-40"
      >
        Next
      </button>
    </div>
  )
}
